FROM mcr.microsoft.com/dotnet/sdk:5.0

WORKDIR /src/

ENV PATH ${PATH}:/root/.dotnet/tools

COPY BumpVersion/ ./

RUN dotnet pack && \
    dotnet tool install --global --add-source /src/nupkg BumpVersion

WORKDIR /test/

COPY BumpVersion.Tests/Docker/.bumpversion.cfg /test/

RUN git init && \
    git add . && \
    git config --global user.email "you@example.com" && \
    git config --global user.name "Your Name" && \
    git commit -m "initial" && \ 
    bumpversion major && \ 
    bumpversion minor && \
    bumpversion patch

CMD ["bash"]