name: Default CI pipeline

on: [push, pull_request]

jobs:
    main:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout code
              uses: actions/checkout@v1

            - name: Set Up .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '5.0.x' # SDK Version to use;

            - name: Test
              run: |
                dotnet test

            - name: Build
              run: |
                dotnet build
